#include <iostream>
using namespace std;
#include <stdio.h>
int main() {
	int n,m;
	int a[12];
	int i,k,j,max,A[100][100],p[100][100],c[100][100];
	int q,r,s,t,cur,g,ins1[10000],ins2[10000],ins3[10000],ins4[10000],ins5[10000];
	
	for(i=0;i<12;i++)
		a[i]=0;
	scanf("%d%d",&n,&m);

	for(i=0;i<n;i++)
		for(j=0;j<m;j++){
			scanf("%d",&p[i][j]);
		}
	for(i=0;i<n;i++)
		for(j=0;j<m;j++){
			scanf("%d",&A[i][j]);
		}
	
	int count=1000000,M;
	
	for(k=1;k<3001;k++){
		M=1;
		for(i=0;i<n;i++)
			for(j=0;j<m;j++){
				c[i][j]=(A[i][j]+k);
				c[i][j]=(c[i][j]%p[i][j]);
				if(c[i][j]!=0){
					M++;
				}
			}
		if(M<count){
			count=M;
			max=k;
		}
	}

	for(i=0;i<n;i++)
		for(j=0;j<m;j++){
			A[i][j]=(A[i][j]+max);
			A[i][j]=(A[i][j]%p[i][j]);
		}
		int lil=1;
		ins1[0]=1;
		ins2[0]=1;
		ins3[0]=n;
		ins4[0]=m;
		ins5[0]=max;
		int de;
		for(i=0;i<n-8;i+=8)
			for(j=0;j<m-8;j+=8){
				de=0;cur=0;
				for(q=0;q<8;q++)
					for(r=0;r<8;r++){
						if((A[i+r][j+q])%p[i+r][j+q]==0)
						de++;
					}
				if(de<20)
					for(k=0;k<3001;k++){
						g=0;
						for(s=0;s<8;s++)
							for(t=0;t<8;t++){
								if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
									g++;
							}
						if(g>cur){
							cur=g;
							max=k;
						}
					}
				if(cur>50){
					count+=de-cur+1;
					ins5[lil]=max;
					ins1[lil]=i+1;
					ins2[lil]=j+1;
					ins3[lil]=i+8;
					ins4[lil]=j+8;
					lil++;
					for(q=0;q<8;q++)
						for(r=0;r<8;r++){
							A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
						}
				}
			}
			for(i=0;i<n-7;i+=7)
				for(j=0;j<m-7;j+=7){
					de=0;cur=0;
					for(q=0;q<7;q++)
						for(r=0;r<7;r++){
							if((A[i+r][j+q])%p[i+r][j+q]==0)
								de++;
						}
					if(de<20)
						for(k=0;k<3001;k++){
							g=0;
							for(s=0;s<7;s++)
								for(t=0;t<7;t++){
									if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
										g++;
								}
							if(g>cur){
								cur=g;
								max=k;
							}
						}
						if(cur>de+16){
							count+=de-cur+1;
							ins5[lil]=max;
							ins1[lil]=i+1;
							ins2[lil]=j+1;
							ins3[lil]=i+7;
							ins4[lil]=j+7;
							lil++;
							for(q=0;q<7;q++)
								for(r=0;r<7;r++){
									A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
								}
						}
				}
	for(i=0;i<n-5;i+=5)
	for(j=0;j<m-5;j+=5)
	{
		de=0;cur=0;
		for(q=0;q<5;q++)
		for(r=0;r<5;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de<20)
		for(k=0;k<3001;k++)
		{
			g=0;
			for(s=0;s<5;s++)
			for(t=0;t<5;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur>de+5)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+5;
		ins4[lil]=j+5;
		lil++;
		for(q=0;q<5;q++)
		for(r=0;r<5;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	if(n%2&&n>6)
		for(i=n-1;i<n;i++)
			for(j=0;j<m;j+=m){
				de=0;cur=0;
				for(q=0;q<m;q++)
					for(r=0;r<1;r++){
						if((A[i+r][j+q])%p[i+r][j+q]==0)
							de++;
					}
				if(de!=m)
					for(k=0;k<3001;k++){
						g=0;
						for(s=0;s<1;s++)
							for(t=0;t<m;t++){
								if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
									g++;
							}
						if(g>cur){
							cur=g;
							max=k;
						}
					}
				if(cur>de){
					count+=de-cur+1;
					ins5[lil]=max;
					ins1[lil]=n;
					ins2[lil]=1;
					ins3[lil]=n;
					ins4[lil]=m;
					lil++;
					for(q=0;q<m;q++)
						for(r=0;r<1;r++){
							A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
						}
					}
			}
	
	if(m%2&&m>6)
	for(i=0;i<n;i+=n)
	for(j=m-1;j<m;j++)
	{
		de=0;cur=0;
		for(q=0;q<1;q++)
		for(r=0;r<n;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de!=m)
		for(k=0;k<3001;k++)
		{
			g=0;
			for(s=0;s<n;s++)
			for(t=0;t<1;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur>de)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=1;
		ins2[lil]=m;
		ins3[lil]=n;
		ins4[lil]=m;
		lil++;
		for(q=0;q<1;q++)
		for(r=0;r<n;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	for(i=0;i<n-6;i+=6)
	for(j=0;j<m;j++)
	{
		de=0;cur=0;
		for(q=0;q<1;q++)
		for(r=0;r<6;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de<2)
		for(k=0;k<200;k++)
		{
			g=0;
			for(s=0;s<6;s++)
			for(t=0;t<1;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur>4)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+6;
		ins4[lil]=j+1;
		lil++;
		for(q=0;q<1;q++)
		for(r=0;r<6;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	for(i=0;i<n;i++)
	for(j=0;j<m-6;j+=6)
	{
		de=0;cur=0;
		for(q=0;q<6;q++)
		for(r=0;r<1;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de<2)
		for(k=0;k<200;k++)
		{
			g=0;
			for(s=0;s<1;s++)
			for(t=0;t<6;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur>4)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+1;
		ins4[lil]=j+6;
		lil++;
		for(q=0;q<6;q++)
		for(r=0;r<1;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
		
		}
	for(i=0;i<n-n%2;i+=2)
	for(j=0;j<m-m%2;j+=2)
	{
		de=0;cur=0;
		for(q=0;q<2;q++)
		for(r=0;r<2;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de!=4)
		for(k=0;k<3001;k++)
		{
			g=0;
			for(s=0;s<2;s++)
			for(t=0;t<2;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
			
		}
		if(cur>de)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+2;
		ins4[lil]=j+2;
		lil++;
		for(q=0;q<2;q++)
		for(r=0;r<2;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	
	
	for(i=0;i<n-3;i+=3)
	for(j=0;j<m;j++)
	{
		de=0;cur=0;
		for(q=0;q<1;q++)
		for(r=0;r<3;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de<2)
		for(k=0;k<200;k++)
		{
			g=0;
			for(s=0;s<3;s++)
			for(t=0;t<1;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur==3)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+3;
		ins4[lil]=j+1;
		lil++;
		for(q=0;q<1;q++)
		for(r=0;r<3;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	for(i=0;i<n;i++)
	for(j=0;j<m-3;j+=3)
	{
		de=0;cur=0;
		for(q=0;q<3;q++)
		for(r=0;r<1;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de<2)
		for(k=0;k<200;k++)
		{
			g=0;
			for(s=0;s<1;s++)
			for(t=0;t<3;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur==3)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+1;
		ins4[lil]=j+3;
		lil++;
		for(q=0;q<3;q++)
		for(r=0;r<1;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	for(i=0;i<n;i++)
	for(j=0;j<m-2;j+=2)
	{
		de=0;cur=0;
		for(q=0;q<2;q++)
		for(r=0;r<1;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de==0)
		for(k=0;k<200;k++)
		{
			g=0;
			for(s=0;s<1;s++)
			for(t=0;t<2;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur==2)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+1;
		ins4[lil]=j+2;
		lil++;
		for(q=0;q<2;q++)
		for(r=0;r<1;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
		for(i=0;i<n-2;i+=2)
	for(j=0;j<m;j++)
	{
		de=0;cur=0;
		for(q=0;q<1;q++)
		for(r=0;r<2;r++)
		{
			if((A[i+r][j+q])%p[i+r][j+q]==0)
			de++;
		}
		if(de==0)
		for(k=0;k<200;k++)
		{
			g=0;
			for(s=0;s<2;s++)
			for(t=0;t<1;t++)
		{
			if((A[i+s][j+t]+k)%p[i+s][j+t]==0)
			g++;
		}
			if(g>cur)
			{cur=g;max=k;}
		}
		if(cur==2)
		{
		count+=de-cur+1;
		ins5[lil]=max;
		ins1[lil]=i+1;
		ins2[lil]=j+1;
		ins3[lil]=i+2;
		ins4[lil]=j+1;
		lil++;
		for(q=0;q<1;q++)
		for(r=0;r<2;r++)
		{
			A[i+r][j+q]=(A[i+r][j+q]+max)%p[i+r][j+q];
		}
		}
	}
	cout<<count<<endl;
	for(i=0;i<lil;i++)
	printf("%d %d %d %d %d\n",ins1[i],ins2[i],ins3[i],ins4[i],ins5[i]);
	
	
	for(i=0;i<n;i++)
	for(j=0;j<m;j++)
	{
		if(A[i][j]!=0)
		{
			printf("%d %d %d %d %d\n",i+1,j+1,i+1,j+1,p[i][j]-A[i][j]);
		}
	}
	return 0;
}         